### ISSUE TITLE
Document how to work with multilingual sites

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-docs#27] opened 2014-11-05 17:58 UTC
Since each language has its specific URL on its specific subdomain, which is stored in the database, if you change the environment (_branching or merging_), you'll break URLs on that environment.

To bypass that, you can create a custom Drush command which you run in your `post-deploy` hook. This command could override the domain of each language to match:
- `[LANGUAGE_CODE]-[PLATFORM_ENVIRONMENT]-[PLATFORM_PROJECT].[CLUSTER].platform.sh`

**Comment by Crell** [comment] 2017-01-23 22:19
That seems like an awful way of handling it. :smile: 

As Drupal 7 and Drupal 8 both have the ability to override configuration from settings.php (with some bugs in D8), shouldn't we instead document how to leverage that?

**Comment by GuGuss** [comment] 2017-01-24 09:51
@Crell You're right, I didn't know you could export those settings :(

**Comment by OriPekelman** [comment] 2017-07-05 10:59
Close this one?

**Comment by Crell** [comment] 2017-07-05 14:42
No, we should get around to building a recommendation here.  It's just never been very high priority.

**Comment by trolologuy** [comment] 2022-05-09 11:37
Given the time that elapsed since the issue was opened, the outdated Drupal version and the evolution of the product, I think it's safe to close the issue.
If there is a reproducible example of such an issue, we can just reopen.

**Closed by trolologuy** 2022-05-09 11:37 UTC
